// A run-through to Week 3, sum by sum, as the game really plays it: every question the pupil meets, with its numbers.
// Run: NODE_PATH=<playwright node_modules> node src/opening/tests/runthrough.test.js   (env: OUT = folder for runthrough.md, UPTO = beat to stop at, default 9)
// The pupil: Paris first, two services at £90 on Launch Day; snacks at £3 on Day 1; just enough fuel; on Day 3 the first service
// moved to 07:00; on Day 4 a Dublin service added; the regular plan approved; the plan kept through Weeks 1–3.
const { chromium } = require('playwright');
const path = require('path'), fs = require('fs'), FILE = 'file://' + path.resolve(__dirname, '../../../airline-opening-prototype.html');
const OUT = (process.env.OUT || require('os').tmpdir()) + '/'; fs.mkdirSync(OUT, { recursive:true });
const UPTO = +(process.env.UPTO || 9);
(async () => {
  const b = await chromium.launch(); const p = await (await b.newContext({ viewport:{ width:1915, height:891 } })).newPage();
  const errors = []; p.on('pageerror', e => errors.push(e.message)); p.on('dialog', d => d.accept());
  await p.goto(FILE); await p.evaluate(() => localStorage.clear()); await p.reload();
  await p.evaluate(() => { const st = window.__sim.settings(); st.flightSecs = 0.25; st.autoWall = false; st.opsSound = false; });
  const T = () => p.evaluate(() => window.__sim.step().t), S = () => p.evaluate(() => window.__sim.S());
  const txt = sel => p.evaluate(s => { const e = document.querySelector(s); return e ? e.innerText.replace(/\s+\n/g, '\n').replace(/[ \t]+/g, ' ').trim() : ''; }, sel);
  const money = v => (v < 0 ? '−' : '') + '£' + Math.abs(Math.round(v)).toLocaleString('en-GB');
  const L = [], q = (kind, what, sum, answer) => L.push(`| ${kind} | ${what} | ${sum.replace(/\n+/g, ' · ').replace(/\|/g, '/')} | ${answer} |`);
  const head = t => L.push('', `### ${t}`, '', '| How | What the pupil is asked | The sum on screen | Answer |', '| --- | --- | --- | --- |');
  const PAIR = { profit:['rev', 'cost', '−'], tk1:['pax1', 'fare1', '×'], tk2:['pax2', 'fare2', '×'], snack:['buyers', 'snackP', '×'], fuel:['fuelL', 'ppl', '×'], empty:['seats', 'flown', '−'], wproj:['profitDay', 'days', '×'], profitDay:['revDay', 'costDay', '−'] };
  // complete every open figure, recording the dock's question and working first
  const solve = async () => { for(let i = 0; i < 20; i++){ const c = await p.$('[data-cell]'); if(!c) break; const id = await c.getAttribute('data-cell'); await c.click(); await p.waitForTimeout(80);
      const row = id.split('|')[1], dock = await txt('.dock .dk-b, .wo-calc');
      const val = await p.evaluate(() => { const t = window.__sim.currentTable(), c = t.cols.find(x => x.id === t.active.col); return c.values[t.active.row]; });
      if(await p.$('[data-pk]')){ const pr = PAIR[row]; q('**Build**', dock.split('\n')[0], `chooses the two figures and the sign (${pr ? pr.join(' ') : '?'}); the model works it out`, typeof val === 'number' ? money(val) : String(val));
        for(const k of pr.slice(0, 2)) await p.click(`[data-pk="${k}"]`); await p.click(`[data-op="${pr[2]}"]`); await p.click('#trySum'); await p.waitForTimeout(100); continue; }
      q('**Typed**', dock.split('\n')[0], dock.split('\n').slice(1).filter(l => !/Type the figure|Confirm figure|Show me/.test(l)).join(' '), typeof val === 'number' && Math.abs(val) >= 10 ? money(val) : String(val));
      await p.evaluate(() => { const t = window.__sim.currentTable(), c = t.cols.find(x => x.id === t.active.col); document.getElementById('cellAns').value = String(c.values[t.active.row]); }); await p.press('#cellAns', 'Enter'); await p.waitForTimeout(80); } };
  const sheet = () => p.evaluate(() => [...document.querySelectorAll('.ws-main table.fx tr')].map(r => [...r.children].map(c => c.innerText.replace(/\s+/g, ' ').replace(/ƒ model/g, '').trim()).filter(Boolean).join(': ')).filter(x => x && !/^Your plan/.test(x)));
  L.push('# The game, Launch Day to Week 3, sum by sum (scripted run)', '', `*Generated by \`src/opening/tests/runthrough.test.js\` on ${new Date().toISOString().slice(0, 10)}.*`, '',
    '**How the pupil meets a sum:**', '',
    '- **Typed:** the pupil works out the figure and types it.',
    '- **Build:** the pupil chooses the two figures and the sign, and the model does the arithmetic.',
    '- **Chosen:** the pupil picks one answer from three on screen.',
    '- **Model:** the game shows the figure and nothing is asked.');
  // ---- setup ----
  await p.click('#start'); await p.fill('#nm', 'Dragon Air'); await p.click('#nx'); await p.click('#nx'); await p.click('#nx'); await p.click('[data-ptab="name"]'); await p.fill('#regIn', 'DRAG'); await p.click('#roll'); await p.click('#skipReveal'); await p.waitForTimeout(150); await p.click('#nx'); await p.click('#nx');
  if(await T() === 'boot') await p.click('#enterHq'); if(await T() === 'chapter') await p.click('#chGo');
  head('Launch Day, Sunday 12 May 2030 (fuel free: the launch deal)');
  q('Model', 'Cash after the aircraft', '£5,000 − £2,500 (shown on the start-up aircraft card)', '£2,500');
  await p.click('#nx'); await p.click('[data-mk="par"]'); await p.click('#nx');
  q('Model', 'Market demand', (await txt('.ws-main .tf-story')) || 'people who want to fly, in aircraft-sized groups', '—'); await p.click('#nx');
  for(let k = 0; k < 4; k++) await p.click('#nx');
  const practiceQ = async title => { const qs = []; for(let i = 0; i < 3; i++){ const a = await p.evaluate(() => window.__sim.practiceAnswer()); if(!a || !(await p.$('#pqIn'))) break; qs.push((await txt('.pq-q')) + ' → ' + a.text); await p.fill('#pqIn', a.text); await p.click('#pqCheck'); await p.waitForTimeout(1050); } q('**Typed**', title, qs.join(' · '), '—'); };
  await practiceQ('One service: when is it ready to fly again? (three practice questions)');
  await p.click('#nx'); await p.click('#nx');
  await p.click('[data-svc="par|2"]');
  let guard = 0, last = '';
  while(guard++ < 400){
    const t = await T(), s = await S(); if(s.round >= UPTO || t === 'protoEnd') break;
    const where = `${t}@${s.round}@${s.si}`; if(where === last) await p.waitForTimeout(250); last = where;
    const R = s.round, setup = s.phase === 'setup';
    if(t === 'intro'){ const key = s.steps[s.si].key; for(let pg = 0; pg < 2; pg++) await p.click('#niNext');
      if(await p.$('#pqIn')){ await practiceQ(`What's new (${key}): three practice questions`); await p.click('#nx'); continue; }
      const qq = await txt('.ni-q'), opts = await p.$$eval('[data-ni]', e => e.map(x => x.textContent.trim()));
      for(let k = 0; k < opts.length && await p.$eval('#nx', e => e.disabled); k++) await p.click(`[data-ni="${k}"]`);
      q('**Chosen**', `What's new (${key}): which sum?`, `${qq} · options ${opts.join(' / ')}`, (await txt('.ni-yes')).replace('✓ ', '') + ' (the game shows the answer; nothing is worked out)'); await p.click('#nx'); continue; }
    if(t === 'chapter'){ head('Chapter banner'); await p.click('#chGo'); continue; }
    if(t === 'event'){ head((await txt('h1, .tf-q')) + ' (event)'); q('Model', 'Decide', 'the choice is made; a cash option joins the day\'s costs'); await p.click('[data-o="1"]'); await p.click('#nx'); await p.click('#nx'); continue; }
    if(t === 'shop2'){ head('Aircraft for sale'); q('Model', 'Look at the aircraft, or not today', 'this run-through keeps one aircraft'); await p.click('#skipShop'); continue; }
    if(t === 'chapterReview'){ head('Chapter accounts'); await solve(); if(await p.$('#calcDone')) await p.click('#calcDone'); await p.click('#nx'); continue; }
    if(t === 'hq'){ head(await p.evaluate(() => { const S = window.__sim.S(); return (S.period.type === 'day' ? `Day ${S.round} · ` : '') + window.__sim.periodLabel(); })); await p.click('#startDay'); continue; }
    if(t === 'milestone'){ head((await txt('.ms-in h1')) + ' (milestone)'); q('Model', 'Read the milestone', (await txt('.ms-in')).split('\n').slice(2, 4).join(' '), '—'); await p.click('#msGo'); continue; }
    if(t === 'review'){ const before = L.length; await solve(); if(L.length === before) q('Model', 'Review last week', 'no figure is asked', '—'); await p.click('#nx'); continue; }
    if(t === 'workout'){
      if(R === 1) await p.click('[data-pe="0|ob|low|0"]');
      if(R === 3) for(let k = 0; k < 4; k++) await p.click('[data-pe="0|dep|0|-1"]');   // 09:00 → 07:00
      if(R === 4) await p.click('[data-pe="0|add|dub|0"]').catch(() => {});
      q('Model', 'Plan', (await txt('.pe-sum, .svcs')) + ' · ' + (await p.evaluate(() => window.__sim.S().deps ? 'departures ' + window.__sim.S().deps.map(m => String(Math.floor(m / 60)).padStart(2, '0') + ':' + String(m % 60).padStart(2, '0')).join(', ') : '')), '—');
      await solve(); if(await p.$('[data-wpick]:not([disabled])') && !(await p.$('[data-wpick].on'))){ const w = await p.$$eval('[data-wpick]', e => e.map(x => x.textContent.trim())); q('**Chosen**', 'Which option?', `options ${w.join(' / ')}`, w[1] || w[0]); await p.click('[data-wpick]:nth-child(2), [data-wpick]'); await p.waitForTimeout(120); await solve(); }
      if(await p.$('#calcDone')) await p.click('#calcDone'); await p.waitForTimeout(120); const rows = await sheet();
      q('Model', 'The rest of the sheet', rows.filter(r => !/Complete figure/.test(r)).join(' · '), '—'); await p.click('#nx'); continue; }
    if(t === 'testIdeas'){ q('Model', 'Test other ideas (optional; the model costs them)', 'flies the plan as planned', '—'); await p.click('[data-fmine]'); continue; }
    if(t === 'fuelPlan'){ if(await p.$eval('#nx', e => e.disabled)) await p.click('[data-oq]:nth-child(2)'); if(await p.$('#fbIn')){ const v = await p.evaluate(() => String(window.__sim.S().rnd.fuelOrder.total)); q('**Typed**', 'Fuel order cost: litres × price per litre', await txt('.ff-bill'), '£' + v); await p.fill('#fbIn', v); await p.click('#fbCheck'); await p.waitForTimeout(120); }
      q('Model', 'Fuel order', (await txt('.ff-parts')) + ' · ' + (await txt('.ff-bill')), '—'); await p.click('#nx'); continue; }
    if(t === 'paint'){ await p.click('#roll'); continue; }
    if(t === 'reveal'){ await p.click('#skipReveal'); for(let i = 0; i < 50 && await p.$eval('#nx', e => e.hidden); i++) await p.waitForTimeout(100); await p.click('#nx'); continue; }
    if(t === 'takeoff'){ await p.click('#toGo'); for(let i = 0; i < 200 && await p.$eval('#nx', e => e.hidden); i++) await p.waitForTimeout(100); await p.click('#nx'); continue; }
    if(t === 'ready'){ await p.click('#startOps'); continue; }
    if(t === 'fly' || t === 'sim'){ for(let i = 0; i < 120 && ['fly', 'sim'].includes(await T()); i++) await p.waitForTimeout(250); continue; }
    if(t === 'results'){ const r = await S(), fl = (r.rnd.flights || []).filter(f => !f.grounded), fuelL = fl.reduce((a, f) => a + (f.fuelL || 0), 0);
      const v = r.rnd.sim ? `${r.rnd.sim.pax} passengers · revenue ${money(r.rnd.sim.rev)} · costs ${money(r.rnd.sim.costs)} · profit ${money(r.rnd.sim.profit)}` : `${fl.reduce((a, f) => a + f.sold, 0)} passengers · revenue ${money(r.rnd.revenue)} · costs ${money(r.rnd.costs)} · profit ${money(r.rnd.profit)}${fuelL ? ` · fuel ${fuelL} L` : ''}`;
      q('Model', 'Results', `${v} · cash ${money(r.cash)}`, '—'); await p.click('#nx'); continue; }
    if(t === 'rop'){ head('End of Day 4: the regular operating plan'); q('Model', 'Approve the plan', 'nothing to work out', '—'); await p.click('#ropGo'); continue; }
    await p.click('#nx').catch(() => {});
  }
  // the count
  const rowsQ = L.filter(l => /^\| (\*\*|Model)/.test(l)), cnt = k => rowsQ.filter(l => l.startsWith(`| ${k}`)).length;
  L.push('', '## Count', '', '| How | Number |', '| --- | --- |', `| Typed | ${cnt('**Typed**')} |`, `| Build | ${cnt('**Build**')} |`, `| Chosen | ${cnt('**Chosen**')} |`, `| Shown by the model | ${cnt('Model')} |`);
  if(errors.length) L.push('', 'Errors: ' + errors.join(' | '));
  fs.writeFileSync(OUT + 'runthrough.md', L.join('\n') + '\n');
  console.log(`wrote ${OUT}runthrough.md · typed ${cnt('**Typed**')} · build ${cnt('**Build**')} · chosen ${cnt('**Chosen**')} · errors ${errors.length ? errors.join(' | ') : 'none'}`);
  await b.close(); process.exit(errors.length ? 1 : 0);
})();
